import assert from 'node:assert/strict';
import type { Page } from 'playwright';
import { STORAGE_KEY } from '../storage';

export async function journeySmoke(page: Page, completedSave: string, artifactDir: string): Promise<void> {
  await page.evaluate(({ key, raw }) => localStorage.setItem(key, raw), { key: STORAGE_KEY, raw: completedSave });
  await page.reload({ waitUntil: 'networkidle' });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const cash = async () => Number((await page.locator('#wallet-value').innerText()).replace(/[^0-9]/g, ''));
  const quantity = async (value: number) => { await page.locator('#quantity').fill(String(value)); await page.locator('#quantity').press('Tab'); };
  const order = async (value: number, price: number) => { await quantity(value); await page.locator(`#price-${price}`).click(); };
  const sell = async () => { await page.locator('#open-market').click(); await page.locator('#skip-sales').click(); };
  const next = async () => { await page.locator('#next-day').click(); };
  const capture = async (name: string) => {
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth);
    assert.equal(overflow, false, name);
    await page.screenshot({ path: `${artifactDir}/${name}.png`, fullPage: true });
  };
  const choose = async (market: string, equipment: string) => {
    await page.locator('#new-market').click();
    await page.locator('#choose-market').click();
    await page.locator(`#equipment-${equipment}`).click();
    assert.equal(await page.locator(`#equipment-${equipment}`).getAttribute('aria-pressed'), 'true');
    await page.locator(`#destination-${market}`).click();
    assert.equal(await cash(), 18000);
    assert.equal(await page.locator('.shop-sign').count(), 1);
    await page.waitForFunction(() => {
      const img = document.querySelector<HTMLImageElement>('.scene-art');
      return img?.complete && img.naturalWidth > 0;
    });
    await page.reload({ waitUntil: 'networkidle' });
    assert.equal(await page.locator('.shop-sign').count(), 1);
  };

  await page.setViewportSize({ width: 1440, height: 1000 });
  assert.equal(await page.locator('.shop-sign').count(), 1);
  await capture('14-desktop-grown-shop');
  await page.locator('#new-market').click();
  await page.locator('#choose-market').click();
  await capture('15-desktop-destinations');
  await page.setViewportSize({ width: 390, height: 844 });
  await capture('16-mobile-destinations');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#new-market').evaluate(el => el === document.activeElement), true);

  await choose('park-walk', 'basic');
  assert.ok((await page.locator('.eyebrow').first().innerText()).includes('공원 장터'));
  assert.equal(await page.locator('#price-2400').count(), 1);
  await order(12, 2400); await sell(); await next();
  await order(6, 4500);
  await page.locator('#accept-booking').click();
  await page.reload({ waitUntil: 'networkidle' });
  assert.equal(await page.locator('#accept-booking').getAttribute('aria-pressed'), 'true');
  await capture('17-mobile-booking-offer');
  await sell();
  assert.equal(await cash(), 69000);
  assert.ok((await page.locator('.booking-result').innerText()).includes('아직 내일 음료를 드려야'));
  await page.locator('#retry-day').click();
  assert.equal(await cash(), 28800);
  await sell(); await next();
  await quantity(0);
  assert.equal(await page.locator('#quantity').inputValue(), '8');
  assert.equal(await page.locator('#less').isDisabled(), true);
  assert.equal(await page.locator('#preset-4').isDisabled(), true);
  await order(11, 3600);
  await page.locator('#open-market').click();
  assert.ok((await page.locator('.selling-panel .booking-due').innerText()).includes('먼저 전달'));
  await page.reload({ waitUntil: 'networkidle' });
  assert.equal(await cash(), 53400);
  assert.ok((await page.locator('.receipt-rows').innerText()).includes('추가 입금 없음'));
  await capture('18-mobile-booking-delivery');
  await next(); await order(11, 3000);
  await page.locator('#accept-booking').click();
  await sell(); await next();
  await order(18, 3600); await sell();
  assert.ok((await page.locator('.result-observation').innerText()).includes('품절로 돌아갔어요'));
  await next();

  await choose('park-concert', 'pantry');
  await order(5, 4500); await sell(); await next();
  await order(15, 2400); await page.locator('#accept-booking').click(); await sell(); await next();
  await order(18, 3600); await page.locator('#rent-cooler').click();
  assert.ok((await page.locator('.cooler-choice').innerText()).includes('8잔'));
  assert.ok((await page.locator('.cooler-choice').innerText()).includes('3,000원'));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await capture('19-desktop-pantry-and-order');
  await sell();
  assert.ok((await page.locator('.storage-result').innerText()).includes('8잔'));
  await next(); await page.reload({ waitUntil: 'networkidle' });
  assert.ok((await page.locator('.carried-stock').innerText()).includes('8잔'));
  await order(0, 4500); await sell(); await next();
  await order(12, 3600); await sell(); await next();
  assert.equal(await cash(), 106800);

  await choose('park-walk', 'tea');
  assert.ok((await page.locator('.panel-eyebrow').innerText()).includes('레몬티'));
  assert.ok((await page.locator('.field-heading').innerText()).includes('2,100원'));
  await order(7, 4500);
  await capture('20-desktop-tea');
  await page.setViewportSize({ width: 390, height: 844 });
  await capture('21-mobile-tea');
  await sell(); assert.equal(await cash(), 34800);
  await next(); await order(6, 3600); await sell(); await next();
  await order(4, 4500); await sell(); await next();
  await order(13, 4500); await sell(); await next();
  await order(12, 4500); await sell(); await next();
  assert.equal(await cash(), 115500);
  await page.locator('#final-journal').click();
  assert.equal(await page.locator('.journey-records li').count(), 3);
  assert.ok((await page.locator('.journey-records').innerText()).includes('115,500원'));
  await capture('22-mobile-journey-records');
  await page.keyboard.press('Escape');
  await page.locator('#new-market').click(); await page.locator('#replay-market').click();
  await page.locator('#restart').click(); await page.locator('#confirm-reset').click();
  assert.equal(await cash(), 18000);
  assert.equal(await page.locator('.shop-sign').count(), 1);
  assert.ok((await page.locator('.panel-eyebrow').innerText()).includes('레몬티'));
  await page.locator('#journal').click();
  assert.equal(await page.locator('.journey-records li').count(), 3);
  await page.keyboard.press('Escape');
}
